Repository opendevstack/ods-provisioning-app, pull requests merged in 2020-07, with the labels that each got.

#502 Pass ODS namespace to Jenkins pipeline
  ocp-config/cm.yml
  src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java
  src/main/resources/application.properties
  src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java
Labels: bug

#541 Use @DirtiesContext everywhere
  src/test/java/org/opendevstack/provision/authentication/crowd/ProvAppSimpleCachingGroupMembershipManagerTest.java
  src/test/java/org/opendevstack/provision/authentication/filter/SSOAuthProcessingFilterBasicAuthHandlerTest.java
  src/test/java/org/opendevstack/provision/authentication/filter/SSOAuthProcessingFilterTest.java
  src/test/java/org/opendevstack/provision/authentication/oauth2/MethodSecurityConfigurationTest.java
  src/test/java/org/opendevstack/provision/authentication/oauth2/Oauth2AuthenticationManagerTest.java
  src/test/java/org/opendevstack/provision/authentication/oauth2/ProvAppExpressionHandlerTest.java
  src/test/java/org/opendevstack/provision/controller/ApplicationInfoAPIControllerTest.java
  src/test/java/org/opendevstack/provision/controller/DefaultControllerTest.java
  src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerSecurityTest.java
  src/test/java/org/opendevstack/provision/controller/E2EProjectAPIControllerTest.java
  src/test/java/org/opendevstack/provision/controller/ProjectApiControllerTest.java
  src/test/java/org/opendevstack/provision/services/BitbucketAdapterTest.java
  src/test/java/org/opendevstack/provision/services/JiraAdapterTests.java
  src/test/java/org/opendevstack/provision/util/rest/RestClientTest.java
Labels: bug

#542 Change contribution flow
  Jenkinsfile
  docs/modules/provisioning-app/pages/architecture.adoc
  ocp-config/README.md
  ocp-config/Tailorfile
  ocp-config/bc.yml
  ocp-config/cm.yml
  ocp-config/dc.yml
  ocp-config/is.yml
  ocp-config/ods-provisioning-app.env.sample
  ocp-config/pvc.yml
  ocp-config/route.yml
  ocp-config/secret.yml
  ocp-config/svc.yml
Labels: enhancement

#545 Unit test for loading indicator
  client/src/app/modules/loading-indicator/components/loading-indicator.component.spec.ts
Labels: frontend-spa

#544 Update client README
  client/README.md
Labels: frontend-spa

#553 Add client codeowner
  CODEOWNERS
Labels: frontend-spa

#546 Unit test for sidebar
  client/src/app/modules/sidebar/components/sidebar.component.html
  client/src/app/modules/sidebar/components/sidebar.component.spec.ts
  client/src/app/modules/sidebar/components/sidebar.component.ts
  client/src/app/modules/sidebar/sidebar.module.ts
Labels: frontend-spa

#554 Pass ODS_BITBUCKET_PROJECT to jobs
  src/main/java/org/opendevstack/provision/services/JenkinsPipelineAdapter.java
  src/test/java/org/opendevstack/provision/services/JenkinsPipelineAdapterTest.java
Labels: bug

#551 Disable new component form on non-openshift projects
  client/src/app/modules/project-page/components/header.component.html
  client/src/app/modules/project-page/components/header.component.spec.ts
  client/src/app/modules/project-page/components/header.component.ts
  client/src/app/modules/project-page/components/project-page.component.html
  client/src/app/modules/project-page/components/quickstarter-list.component.html
  client/src/app/modules/project-page/components/quickstarter-list.component.spec.ts
  client/src/app/modules/project-page/components/quickstarter-list.component.ts
Labels: frontend-spa

#555 Update architecture.adoc with new frontend UI info
  docs/modules/provisioning-app/pages/architecture.adoc
Labels: frontend-spa

#557 Layoutfix Safari
  client/src/app/ui/scss/components/_page.scss
Labels: bug, frontend-spa

#558 Font fixes
  client/src/app/ui/scss/theme/default/_typo.scss
  client/src/index.html
Labels: frontend-spa
